### PR TITLE
Added support for custom buildpacks

### PR DESCRIPTION
**Pull request by jkutner**

### CODE REVIEW

**Comment by dragoninfrontofme** [comment]
Hi Joe,

I tried this changes, it works :)
But just want to add some comment:
in order to use this in Heroku: 
1. we need to add "heroku-buildpack-multi" to the app
    "heroku config:set BUILDPACK_URL=https://github.com/ddollar/heroku-buildpack-multi"
2. then need to specify the based buildpack:
    herokuBuildpacks in Compile := Seq(
        "https://github.com/mcollina/heroku-buildpack-graphicsmagick",
        "https://github.com/heroku/heroku-buildpack-scala"
    )
3. In my case, im using scala buildpack, but it can be applied for all buildpack

Thank you very much for the helps! hope i can contribute something for this git! very useful :)

Regards
Lucius

**Comment by jkutner** [comment]
@dragoninfrontofme when using sbt-heroku, you will not need the heroku-buildpack-scala, only the jvm-common entry like this: https://github.com/heroku/sbt-heroku/blob/master/src/sbt-test/settings/buildpacks/build.sbt#L21-L24

Also, you should not need to use heroku-buildpack-multi anymore. This tool just uses the `herokuBuildpacks` list instead. 

I'm glad it worked

**Comment by dragoninfrontofme** [comment]
Hi Joe, 

Oh ok, well noted, i will do necessary changes on my end

Thank you

**Comment by dragoninfrontofme** [comment]
HI Joe

Just quick question, i am quite new with scala and heroku, would the buildpack under herokuBuildpacks setting be executed? because i am facing problem that graphicmagick "https://github.com/mcollina/heroku-buildpack-graphicsmagick" was not executed, not really sure how buildpack works. but i still looking around the solution to make it work. Currently when i run my app "gm" (command for graphicsmagick) was not found.

appreciate if you have any idea, if not then just ignore my question :)

Thank you

**Comment by jkutner** [comment]
@dragoninfrontofme can you open a [support ticket](http://help.heroku.com) (or maybe another one, haha) and share the name of your app? That way I can take a closer look at things.

**Pull request merged**
