### PR TITLE
Remove Scala compiler from `libraryDependencies`

### PR DESCRIPTION
**Pull request by y-yu**
- I cannot use `sbt-heroku` in Scala 3 project due to this error:
    ```console
    [info] [error] sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala-compiler:3.0.1
    [info] [error]   Not found
    [info] [error]   Not found
    [info] [error]   not found: /Users/yyu/.ivy2/local/org.scala-lang/scala-compiler/3.0.1/ivys/ivy.xml
    ```
- Actually I didn't know why `scala-compiler` had been added to `libraryDependencies` 🤔 
- I add Scala 3 + akka-http test
- Work around:
    - https://github.com/y-yu/kindle-clock/blob/4d0877076cd95bbe0d75046f0691327680fad908/build.sbt#L158-L163

### CODE REVIEW

**Comment by y-yu** [comment]
How do I do to run CI? 🤔

**Comment by xuwei-k** [comment]
https://github.com/heroku/sbt-heroku/commit/1bd2bbd87143ad25e8329ef38f92a2a636acc243
🤔

**Review by DanielDispatchIT — APPROVED** [review]
Looks good! Let's see if we can get someone to merge the PR. I have the same issue and this fix would be great.

**Comment by y-yu** [comment]
@Malax 
Please check Circle CI setting of this repository 🙏

**Review by edmorley — COMMENTED** [review]
(I'm about to enable review reminder for team-alias reviews, so I'm switching any reviews that need language-owner review to the owner directly, to prevent reminders the rest of the team can't action)

**Comment by y-yu** [comment]
I will remove akka dependencies in test due to the license change: https://github.com/akka/akka/pull/31561 .

**Comment by Malax** [comment]
Closing this PR because this repository will be archived. See https://github.com/heroku/heroku-jvm-application-deployer for an alternative CLI to deploy locally compiled Scala applications.

**Pull request closed without merging**
